### ISSUE TITLE
Expose "options"

### ISSUE THREAD

**Issue by davesc** [PyAV-Org/PyAV#178]
I'm having trouble figuring out how to pass arguments to ffmpeg. I think this might be a documentation issue (for a low level hack like me).  For example, can I set the keyframe interval in an output video?  In ffmpeg I would use something like -g 1 to force every frame to be a keyframe. Can you use an ffmpeg argument string with PyAV?

**Comment by mikeboers** [comment]
I think that is [AVCodecContext.gop_size](https://ffmpeg.org/doxygen/trunk/structAVCodecContext.html#a9b6b3f1fcbdcc2ad9f4dbb4370496e38), which is not currently exposed. It could be easily added to that object, but...

Your question made me go investigate a few things, and I think that taking advantage of as much of the machinery that the `ffmpeg` command uses as possible would be wonderful, instead of having to re-invent everything.

[Here are all of the options on AVCodecContext](https://ffmpeg.org/doxygen/trunk/libavcodec_2options__table_8h_source.html#l00036), which includes "gop_size" that is set via "g".

If all classes took a look at their `AVClass`, perhaps a generic `xxx.set_option(name, value)` would do nicely. It could also be wrapped into a mapping interface.

[ ] Investigate how `ffmpeg` command uses options.
[ ] Design how to expose this for all types.
[ ] Implement it.

**Comment by davesc** [comment]
Exposing the ffmpeg command line options would be super useful!

For now I'll try adding options as I need them... although, that might be way above my coding level

**Comment by rjeli** [comment]
Hi @mikeboers, was this implemented?

**Comment by mikeboers** [comment]
_reads this again_

No. No it was not.

_reopens it_

**Comment by rjeli** [comment]
Okay, I've just been manually adding getters and setters when a field isn't exposed. I'm not sure if there's a nice way to do it dynamically (getattr and setattr) with Cython. Might have to do some codegen from [that header](https://ffmpeg.org/doxygen/trunk/libavcodec_2options__table_8h_source.html#l00036) :grimacing:

**Comment by SehgalDivij** [comment]
@mikeboers has this been implemented?

**Comment by pwuertz** [comment]
@SehgalDivij Seems so. By setting `codec_ctx.gop_size = 20` on a `CodecContext` I'm getting `is_keyframe is True` on every 20th encoded `Packet`.

**Comment by jlaine** [comment]
@pwuertz seems to have offered a reasonable solution, closing
