### ISSUE TITLE
Decode into specific pix_fmt

### ISSUE THREAD

**Issue by maingoh** [PyAV-Org/PyAV#551]
I would like to decode a yuv420p video into jpeg images as fast as possible.
Decoding with threading auto is quite fast, however when converting to rgb and jpeg it is quite slow.

- I am wondering if the `to_rgb()` use the ffmeg library just like the option `-pix_fmt` does ? Is there some overhead ?
- Converting to jpeg using PIL and `to_image()` is slow, it is faster with cv2 but I would like to know if there is a way for ffmpeg to do everything at once while decoding ? (with threading enabled if possible)

Thank you !

**Comment by mikeboers** [comment]
`to_rgb()` does use FFmpeg, but I doubt it has any capability of threading within a frame. You can run it in your own thread pool (e.g. futures) to achieve that, as the GIL should be released.

I believe it may also be possible to have FFmpeg decode directly into the `pix_fmt` that you want, but I suspect that in most cases that won't actually buy much performance since it is overwhelmingly likely that the `pix_fmt` that it defaults to is the native one for the codec which would need to be converted anyways.

I'll leave this open for now as a feature request to decode directly into the format you want.
