### ISSUE TITLE
Where is the timestamp in the RTSP.

### ISSUE THREAD

**Issue by Mmidgods** [PyAV-Org/PyAV#665]
Hi：

I want to get a stream in the camera and keep the time synchronization, so I need to get the timestamp in RTSP. I've been looking for it for a long time, but I haven't found this method. I want to ask you. I use the windows platform to develop Python programs. thanks

**Comment by jlaine** [comment]
I'm not sure the question is related to `aiortc` itself since you don't seem to mention WebRTC, only RTSP. Anyway, I suggest you look at `PyAV` specifically the `AudioFrame` and `VideoFrame` classes. Frames can carry multiple types of "timestamps", though most likely you are interested in `pts` (presentation timestamp).

**Comment by Mmidgods** [comment]
WorldTime stamp from RTP packet With payload。such as 2020_5_18 15:33:35

**Comment by jlaine** [comment]
I'm not sure what you mean by "WorldTime stamp", RTP only has a concept of a integer timestamp with an arbitrary offset.

**Comment by Mmidgods** [comment]
Sorry, I should get header extensions in RTP.
Here's what wirshark got

    Header extensions
        Header extension: 0xe273039a (3799188378)
        Header extension: 0x3be76c00 (1005022208)
        Header extension: 0x00000000 (0)

**Comment by jlaine** [comment]
I am not convinced FFmpeg gives us access to this information but feel free to browse FFmpeg's RTSP code.

**Comment by Mmidgods** [comment]
OKOK，thanks
