### ISSUE TITLE
Getting h264_omx to work with PyAV

### ISSUE THREAD

**Issue by jpiat** [PyAV-Org/PyAV#688]
Hi,

when using h264_omx to encode video on raspberry-pi with ffmpeg, it works fine but trying to get h264_omx to work within PyAV, calling encode gets stuck and never returns. Using the exact same code with libx264 works fine when building the codec works fine. I swa a lot of issues regarding h264_omx and zero copy but, i can't figure why ffmpeg works fine while the same codec in PyAV does not work.

**Comment by SoundsSerious** [comment]
Hi @jpiat 

We have identical issues on the RaspberryPi 4, specifically we are using PyAV as it integrates with aiortc quite nicely.

Our current thought process is to run ffmpeg in another process like, and use some ffmpeg protocol like UDP, UNIX, or PIPE to bring in 

`ffmpeg -f v4l2 -video_size 640x480 -i /dev/video0 -codec:v h264_omx -b:v 20480k -nostdin  -f matroska -fflags nobuffer udp://0.0.0.0:8899?broadcast=1&connect=1`

Trying to figure out exactly how many methods of input are supported by `av.open(`
#703

**Comment by jlaine** [comment]
@SoundsSerious please don't pollute other tickets.

@jpiat I stumbled upon this too, the root cause is in #751, the logging framework has issues. You can work around this in two ways:

- set the PYAV_LOGGING=off environment variable
- call `av.logging.restore_default_callback()`

Let's track this in #751.
