### ISSUE TITLE
PyAV does not output video stream in expected frame rate and duration when extracting frames from input to output. 

### ISSUE THREAD

**Issue by HaujetZhao** [PyAV-Org/PyAV#709]
## Overview

In the example below, I extract the even frames (dropping the odd frames) from the input to the output.

The input frame rate is 30fps, and it's duration is 60s.

So the expected output frame rate is expected to be 30fps, and the duration should be 30s.

But the result from pyav is not as expected. The fps remains 30fps and the output duration became 57.37s, it's just the tbr became 15 from 30.

Here is the code:

```Python
import av

inputFile = 'test.mkv'
outputFile = 'test_out.mkv'


container_in = av.open(inputFile) # the input framerate is 30fps, duration is 60s.
container_in.streams.video[0].thread_type = 'AUTO'

container_out = av.open(outputFile, mode='w')
stream = container_out.add_stream('libx264', rate=30, options={"crf":"23"})
# stream = container_out.add_stream('libx264', rate=30, options={"crf":"23", 'r':'30'})

stream.width = container_in.streams.video[0].codec_context.width
stream.height = container_in.streams.video[0].codec_context.height
stream.pix_fmt = container_in.streams.video[0].codec_context.pix_fmt

for count, frame in enumerate(container_in.decode(video=0)):
    if count % 2 == 0:
        # only the even number frame will be written to the out put
        # so the expected output is like 2x of input
        # the frame rate is expected to be 30fps, and the duration is expected to be 30s
        container_out.mux(stream.encode(frame))
        print(count)

container_in.close()
container_out.close()


# The expected output video should have the framerate 30fps, but instead of generating new timestamp, the output frames just copied the input timestamp.
# Even if I use the {'vsync':'drop'} stream option, the output still won't change.
# This behavior is so different from using CLI.
```

## Expected behavior

The input video stream is:

```
Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 2160x1440, 30 fps, 30 tbr, 1k tbn, 60 tbc (default)
    Metadata:
      DURATION        : 00:01:00.066000000
```

The output video stream is expected to be:

```
Stream #0:0: Video: h264 (High), yuv420p(progressive), 2160x1440, 30 fps, 30 tbr, 1k tbn, 60 tbc (default)
    Metadata:
      DURATION        : 00:00:30.033000000
```

## Actual behavior

But the actual output video stream is:

```
Stream #0:0: Video: h264 (High), yuv420p(progressive), 2160x1440, 30.30 fps, 15 tbr, 1k tbn, 60 tbc (default)
    Metadata:
      DURATION        : 00:00:57.366000000
```

**Comment by kishorepv** [comment]
When you change frame rate the total duration of the video still does not change. Isn't that how it should be?

**Comment by FirefoxMetzger** [comment]
You are forgetting about a frame's `pts` (presentation time stamp). This indicates at which time the frame should be shown to the user and the last frame's `pts` determines the length of your video. If you drop even frames but leave `pts` unchanged then the final video will still be 60s long (or 57.37s, because you dropped the frame at 60s), because that's simply the value of the last frame's `pts` and ffmpeg will faithfully honor this.

Your video stream's FPS will also remain at 30 FPS; however, instead of presenting a new frame 30 times per second you end up skipping every other "slot" where you could present a frame. As a result, your _effective_ framerate will be 15 FPS (30 FPS base, but every other frame is blank) and `rbr` will report this _effective_ framerate. This behavior is actually [plastered all over FFmpeg's source](https://ffmpeg.org/doxygen/4.1/structAVStream.html#ad63fb11cc1415e278e09ddc676e8a1ad), but frequently ignored non-the-less.

So in sum, the solution to this behavior is to retime your frames:

```python
```

**Comment by jlaine** [comment]
What FFmpeg version is this, as this might be related to the test failures we get against FFmpeg 4.4?

See #876
