### ISSUE TITLE
Use of sws_getCachedContext's caching can be ineffective

### ISSUE THREAD

**Issue by malc0** [PyAV-Org/PyAV#74]
FFMPEG's sws_init_context can modify the opaque SwsContext parameter without the caller knowing (in my case it modifies srcFormat and srcRange and prints "deprecated pixel format used, make sure you did set range correctly").  Because PyAV can't see this change, and srcFormat is compared in sws_getCachedContext, the cache test is failed and the context destroyed and recreated (and the warning printed) on every frame.

Modifying av/video/frame.pyx to test `if not self.reformatter.ptr:` before conditionally calling lib.sws_getCachedContext() fixes it for me, but I guess could have undesirable behaviour without checking the arguments to lib.sws_getCachedContext are unchanged.

For reference, the ffmpeg binary doesn't take this path, but instead calls sws_init_context directly from libavfilter/vf_scale.c.

**Comment by markreidvfx** [comment]
can you provide some example python code where this issue occurs?

**Comment by malc0** [comment]
Sure.  To get my exact issue the code below requires a clip with frames encoded in YUVJ420: I've put such a clip (7 MB) at http://sb476.user.srcf.net/yuvj420p.mov

```python
import av

input = av.open('yuvj420p.mov')

output = av.open('out.mp4', 'w')

outstream = output.add_stream('mpeg4', '50')
outstream.bit_rate = 4000000
outstream.pix_fmt = 'yuv420p'
outstream.width = 1920
outstream.height = 1080

for packet in input.demux():
    for frame in packet.decode():
        output.mux(outstream.encode(frame))

output.close()
```

**Comment by mikeboers** [comment]
Aside: I'd like to find such an example in the FATE suite, OR, can we have your permission to hang on to this one to integrate permanently?

**Comment by malc0** [comment]
Haven't searched through everything, but mjpegb/mjpegb_part.mov appears to behave the same.

**Comment by markreidvfx** [comment]
I'm able to replicate the issue on my end. The cache miss is happening because [sws_init_context](https://www.ffmpeg.org/doxygen/2.1/libswscale_2utils_8c_source.html#l01084) changes the src pix_fmt yuvj420p -> yuv420p in [handle_jpeg](https://www.ffmpeg.org/doxygen/2.1/libswscale_2utils_8c_source.html#l01017). 

This is really a issue with the decoder, it shouldn't be using the deprecated format and instead use yuv420p and set the correct color range via [av_frame_set_color_range] (https://www.ffmpeg.org/doxygen/2.3/group__lavu__frame.html#ga862e9789b46539b3edcf0ae4cb106f95) or something like that.  I think we are correct in using sws_getCachedContext (but we should add null check the after the call) as it eliminates us having to write a bunch of code.

If I force the src pix_fmt to yuv420p it works, maybe exposing the src pix format as a optional kwarg, or allow changing of the AVFrame format via a property is a solution.

**Comment by jmoraleda** [comment]
This warning is still appearing in the latest version.

**Comment by malc0** [comment]
This problem is still present in the PyPI v9.2.0 binary wheel, using Python 3.9.
